[window]
decorations = "None" 
option_as_alt = "Both"

[font]
size = 18
[font.bold]
family = "PlemolJP Console NF"
style = "Bold"

[font.bold_italic]
family = "PlemolJP Console NF"
style = "Bold Italic"

[font.italic]
family = "PlemolJP Console NF"
style = "Italic"

[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

# moving between tmux windows cmd+a, cmd+s, cmd+d etc..
[[keyboard.bindings]]
key = "A"
mods = "Command"
chars = "\u001ba"

[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u001bs"

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u001bd"

[[keyboard.bindings]]
key = "F"
mods = "Command"
chars = "\u001bf"

[[keyboard.bindings]]
key = "G"
mods = "Command"
chars = "\u001bg"

[[keyboard.bindings]]
key = "Z"
mods = "Command"
chars = "\u001bz"

[[keyboard.bindings]]
key = "X"
mods = "Command"
chars = "\u001bx"

[[keyboard.bindings]]
key = "C"
mods = "Command"
chars = "\u001bc"

[[keyboard.bindings]]
key = "V"
mods = "Command"
chars = "\u001bv"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"
[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
